### ISSUE TITLE
Falsche Formulierung S. 10 - "der Selbigen"

### ISSUE THREAD

**Issue by danthp1** [Delors/delors.github.io#1]
S.10: 
Original: 
Konsistenz und Replikation: Welcher Tradeoffs müssen in Hinblick auf die
Konsistenz der Daten, der Replikation der Selbigen und der Performance getroffen
werden?

Sollte so lauten:
Welcher Trade-offs müssen in Hinblick auf die Konsistenz der Daten, der Replikation derselben und der Performance getroffen werden?

Da es sich um keine formelle Anrede handelt, sondern das Wort "selbigen" als Pronomen verwendet wird, das sich auf „Daten“ bezieht, muss dieses kleingeschrieben werden oder das Wort „derselben“ oder "derjenigen" verwendet werden.

**Comment by Delors** [comment]
Danke!  Im nächsten Release behoben.
