### ISSUE TITLE
Fehler

### ISSUE THREAD

**Issue by HannahHaubner** [Delors/delors.github.io#10]
Folie 31:
Leerzeichen zwischen D. h.

**Comment by HannahHaubner** [comment]
S. 39:
Kommasetzungsfehler:
Sie sind Pentester und versuchen in ein System einzudringen**,** indem

**Comment by HannahHaubner** [comment]
s. 40 
Fehlender Punkt beim dritten Bulletpoint:  Die Laufzeitumgebung übernimmt die Partitionierung der Eingabedaten und Verteilung selbiger auf die Rechner des Clusters "."

**Comment by HannahHaubner** [comment]
S 45:

Bindestrich zwischen "2000er-Jahren" fehlt

**Comment by HannahHaubner** [comment]
S. 47 :

Tippfehler: Die direkte Kommunikation zwischen den Anwendung**en** führt zur Integration von
Unternehmensanwendungen (Enterprise Application Integration (EAI)).

**Comment by HannahHaubner** [comment]
S. 49 

Fehlendes t bei oft : Daten, die im Rahmen einer Transaktion benötigt werden, sind of**t** verteilt über mehrere Server.

**Comment by HannahHaubner** [comment]
Folien: "Formale Analyse der Skalierbarkeit zentralisierter Systeme" fehlen (erste Folie mit dem Titel vorhanden, Rest nicht)

**Comment by Delors** [comment]
Eigentlich gehört sowohl zwischen d. h. und z. B. ein "Thin-No-Break-Space" - Sie haben mich jetzt motiviert dies überall einzusetzen. Allerdings mag das nicht jeder Browser gleich handhaben....

2000er Jahre ist korrekt (§42 - Ausnahme) https://grammis.ids-mannheim.de/rechtschreibung/6159#

Danke! Tippfehler sind im nächsten Release behoben. (An dem "fehlende Folie" Problem arbeite ich jedoch noch.)
