### ISSUE TITLE
Fehler/Umformulierungen

### ISSUE THREAD

**Issue by Leon-Sln** [Delors/delors.github.io#18]
[  ] 9: architekturellen (klein schreiben)
[  ] 9: welche tradeoffs (nicht welcher)
[  ] 14: Operation durchgeführt hat, bevor (Komma)
[  ] 15: offen zu legen, kann (Komma)
[  ] 15: nicht antwortet, kann (Komma)
[  ] 16: anderswoher -> besser: woanders
[  ] 28: Skalierbarkeit bzgl der Größe (nur 1x "der")
[  ] 30: auf eine Anfrage lange auf auf die Antwort (macht kein sinn ???)
[  ] 35: toleriert werden können, ist ...  (Komma)
[  ] 46: Aktualität (falsch geschrieben)
[  ] 53: 4. -> selbst (statt selber)
[  ] 54: Aktueller Stand ist (groß schreiben)

**Comment by Delors** [comment]
Danke - im nächsten Release behoben.

**Comment by Delors** [comment]
Done
