### ISSUE TITLE
Weitere Fehler: 

### ISSUE THREAD

**Issue by PhilSimon123** [Delors/delors.github.io#19]
(Die Textstellen einfach mit CMD + F suchen)

**Comment by PhilSimon123** [comment]
<img width="454" alt="image" src="https://github.com/Delors/delors.github.io/assets/160123439/cf2b6fb2-cb9d-4adf-a5a1-736c78a3f18b">

Punkt am Satzende vergessen.

**Comment by PhilSimon123** [comment]
<img width="454" alt="image" src="https://github.com/Delors/delors.github.io/assets/160123439/7279bcb6-e875-4f28-b746-c49851fd89f9">


D. h.   -> Das Problem besteht generell und lässt sich schnell beheben

**Comment by Delors** [comment]
Das Problem mit "D.h." ist bereits behoben. 

Satzende ergänzt.

**Comment by PhilSimon123** [comment]
<img width="312" alt="image" src="https://github.com/Delors/delors.github.io/assets/160123439/e21bf866-a62e-4ab6-9341-b2235facf4ca">

Konsistenz, deshalb großschreiben (oder eben klein)

**Comment by PhilSimon123** [comment]
<img width="454" alt="image" src="https://github.com/Delors/delors.github.io/assets/160123439/1ff3c58b-4ec2-4655-895b-7849f57c4a31">


1.	Leerzeichen bei der ersten Klammer
2.	Anführungszeichen muss unten sein
3.	Inwieweit

**Comment by PhilSimon123** [comment]
<img width="454" alt="image" src="https://github.com/Delors/delors.github.io/assets/160123439/7851a14a-1c7c-4621-a5dc-af4726f4a044">


Setzen

**Comment by PhilSimon123** [comment]
<img width="454" alt="image" src="https://github.com/Delors/delors.github.io/assets/160123439/3a06a9f5-5937-4efc-ac87-7da739f63822">

Müsste im deutschen eigentlich offline heißen

**Comment by PhilSimon123** [comment]
<img width="454" alt="image" src="https://github.com/Delors/delors.github.io/assets/160123439/0e4495b9-95fd-448c-a77a-dd631f8bf671">

Punkte am Satzende vergessen.
P2P-Systemen

**Comment by PhilSimon123** [comment]
<img width="454" alt="image" src="https://github.com/Delors/delors.github.io/assets/160123439/e916dc53-37ad-4593-9aa3-86d03a602f32">

Konsistenz: Oft

**Comment by PhilSimon123** [comment]
<img width="454" alt="image" src="https://github.com/Delors/delors.github.io/assets/160123439/719dedfc-16e9-4864-8940-279ab958090c">

Design-Fehlern oder Designfehlern

**Comment by PhilSimon123** [comment]
<img width="365" alt="image" src="https://github.com/Delors/delors.github.io/assets/160123439/72d43e8e-75b3-408e-8a7e-2bc934e4c980">

Kleinschreibung; null ?

**Comment by PhilSimon123** [comment]
@Delors Weitere Fehler hier, falls noch nicht gesehen.

**Comment by Delors** [comment]
Vielen Dank; Probleme sind mit dem nächsten Update behoben.
