### ISSUE TITLE
Tippfehler Aufgabenstellung

### ISSUE THREAD

**Issue by TomGimp** [Delors/delors.github.io#20]
"Bedenken Sie: „In der Kürze liegt die **Würze!■;** schneiden/beschleunigen Sie Ihr Video, wenn es Abschnitte gibt, die nicht relevant sind."

**Comment by TomGimp** [comment]
"Abgabe
• Pro Gruppe ist eine schriftliche Ausarbeitung zur Architektur und Testkonzept zu erstellen (ca. 3 - 5
Seiten)
• Der Java-Quellcode (mit Kommentaren) und Testdatensätze
• lauffähige class-Dateien mit entsprechenden Initialisierungsdateien sowie einer kurzen
Bedienungsanleitung sind einzureichen (als JAR Datei(en), die direkt gestartet werden kann bzw.
können "java -jar ....")."

Bei Punkt 3 endet die Aufzählung mit einem Punkt, bei 1 nicht :)

**Comment by Delors** [comment]
Danke - ich werde die Beschreibung bei nächster Gel. aktualisieren.
