### ISSUE TITLE
Bild alignment   

### ISSUE THREAD

**Issue by TomGimp** [Delors/delors.github.io#22]
Auf Seite 11 im neuen Skript sind die Säulen der Grafik nicht auf selber Höhe.
Der Port Teil oben ist weiter eingerückt (nach rechts) als die Säule unten.
<img width="374" alt="Screenshot 2024-02-22 at 12 16 13" src="https://github.com/Delors/delors.github.io/assets/57369078/a9926274-1563-4974-8018-c20b46912224">

**Comment by Delors** [comment]
(Hopefully) fixed.
