### ISSUE TITLE
Einheitlichkeit der Zeichensetzung

### ISSUE THREAD

**Issue by Candydog123** [Delors/delors.github.io#24]
In der Aufzählung auf Seite 10 sind nur bei einem der drei Aufzählungspunkte ein Punkt am Satzende. Hier wäre es möglich entweder bei allen Sätzen einen Punkt am Satzende zu verwenden oder den einen Punkt herauszunehmen.

![image](https://github.com/Delors/delors.github.io/assets/80030108/35b99714-d8e5-41c6-b800-2d2c30b64dba)

Gleiches gilt für Slide 8.1
![image](https://github.com/Delors/delors.github.io/assets/80030108/01a835bf-2577-4669-8048-b99feed6079f)

**Comment by Delors** [comment]
Fixed in next release.
