### ISSUE TITLE
Grundlegende Konzepte

### ISSUE THREAD

**Issue by FelixB72** [Delors/delors.github.io#30]
S. 4 unten: Die logische Zeit ermöglicht es uns, eine wohldefinierte ... --> Komma hat gefehlt

**Comment by FelixB72** [comment]
S. 4 unten: ...wohldefinierte Reihenfolge zwischen Ereignissen... --> "n" hat gefehlt

**Comment by FelixB72** [comment]
S. 8 unten: d. h. potentiell unpräziser ist --> Leerzeichen zwischen "d." und "h." hat gefehlt

**Comment by FelixB72** [comment]
S. 11 unten: Es ist wichtig zu wissen, was vorher ... aber es ist nicht wichtig, dass wir wissen, wann genau etwas ... --> zwei Kommas haben gefehlt

**Comment by FelixB72** [comment]
S. 9 unten: Aufgrund der Probleme ist ein ... Schnappschuss nicht realisierbar --> ein "ist" muss aus dem Satz gestrichen werden

**Comment by Delors** [comment]
bei d. h. gibt es leider gelegentlich ein technische Problem mit dem Leerzeichen (es ist ein non-breakable space im Original. 

die restlichen Fehler sind im nächsten Release behoben - Danke.
