### ISSUE TITLE
HTTP und Sockets (in Java) 

### ISSUE THREAD

**Issue by PhilSimon123** [Delors/delors.github.io#33]
Fehler 1: 
Schreiben Sie einen HTTP-Client, der den Server archive.org kontaktiert, die Datei /web/web.php anfordert und die Antwort des Servers auf dem Bildschirm ausgibt.

Fehlendes Komma

Fehler 2: 
Modifizieren Sie Ihren Client, sodass eine URL als Kommandozeilenparameter akzeptiert wird.

sodass statt so dass

Fehler 3: 
Modifizieren Sie Ihr Programm, sodass die Antwort des Servers als lokale Datei abgespeichert wird. Laden Sie die Datei zum Anzeigen in einen Browser.

sodass statt so dass

Fehler 4: 
Schreiben Sie ein UDP-basiertes Java-Programm, mit dem sich Protokoll-Meldungen auf einem Server zentral anzeigen lassen.

Fehlendes Komma vor mit

**Comment by Delors** [comment]
so dass oder sodass ist beides richtig: https://www.duden.de/rechtschreibung/sodass

die anderen Fehler sind im nächsten Release behoben; danke.
