### ISSUE TITLE
Anmerkungen zu den Vorlesungsslides

### ISSUE THREAD

**Issue by FelixB72** [Delors/delors.github.io#9]
S. 10: Warnungsbox:  ... in Bezug auf, z.B. .... --> Komma weg und Leerzeichen zwischen "z." und "B."
S. 11 : Konsistenz und Replikation; Welcher Tradeoffs --> Welche Tradeoffs
S. 13: Gemeinsames Webhosting (z.B. .... --> Leerzeichen zwischen "z." und "B."
S. 14: so genannten --> zusammenschreiben --> sogenannten

**Comment by FelixB72** [comment]
S. 18: [1] Komponenten sein Prozesse oder Kanäle --> seien Prozesse oder Kanäle

**Comment by FelixB72** [comment]
S. 21: 99,999% --> Leerzeichen vor dem %-Zeichen  (kommt 2-mal auf der Seite vor)

**Comment by FelixB72** [comment]
S. 29: Prozeß --> Prozess

**Comment by FelixB72** [comment]
S. 20: Mean Time to Failure ((MTTF)) --> eine Klammer geht zu viel auf

**Comment by FelixB72** [comment]
S. 29:  Die Warteschlange hat eine unendliche Kapazität; d.h. ... --> Leerzeichen zwischen "d." und "h."

**Comment by FelixB72** [comment]
S.40: Seite ist bei etwa der Hälfte abgeschnitten und die untere Hälfte ist nicht sichtbar

**Comment by Delors** [comment]
Danke!  Tippfehler im nächsten Release behoben. 

(so gennant  sollte korrekt sein: https://languagetool.org/insights/de/beitrag/so-genannt-sogenannt/#:~:text=Bis%20zur%20ersten%20großen%20Rechtschreibreform,dass%20beide%20Schreibvarianten%20richtig%20sind.)

An den fehlenden/abgeschnittenen Folien arbeite ich noch.
