### ISSUE TITLE
Middleware Folien Anmerkungen

### ISSUE THREAD

**Issue by FelixB72** [Delors/delors.github.io#90]
S. 49: Publish-Subscribe: Ermöglicht es den Clients, sich ... --> Komma fehlte

**Comment by FelixB72** [comment]
S. 49: Pipeline: Ermöglicht es, eine Aufgabe --> Komma fehlte

**Comment by FelixB72** [comment]
S. 52: POLL Prüft, ob... --> Komma fehlte

**Comment by FelixB72** [comment]
S. 53 unten: Queue Managers sind der zentrale Baustein --> "zentrale" kleinschreiben

**Comment by FelixB72** [comment]
S. 54: ... Mit anderen Worten: ... --> "Worten" großschreiben

**Comment by Delors** [comment]
fixed in the next release
