### ISSUE TITLE
Anmerkungen: Architekturen

### ISSUE THREAD

**Issue by HannahHaubner** [Delors/delors.github.io#91]
S. 3: Ein Mechanismus *,* der die Kommunikation, Koordination oder Kooperation zwischen Komponenten
vermittelt. Beispiel: Einrichtungen für (entfernte) Prozeduraufrufe (RPC), Nachrichtenübermittlung oder
Streaming  -- fehlendes komma 

S. 10 : Ein*e* große Herausforderung ist das Design der Schnittstellen. - fehlendes e

S 17: Sagas können keine Atomizität garantieren!*.*  - Punkt zu viel

S. 21: Was passiert*,* wenn die Middleware nicht erreichbar ist? 
Was passiert*,* wenn das Event nicht verarbeitet werden kann? - jeweils fehlendes Komma

+ Folie 21 sehr unsauber als PDF formatiert

**Comment by Delors** [comment]
behoben im nächsten Release
