### ISSUE TITLE
Missing "g" in href value on slide 5

### ISSUE THREAD

**Issue by GitWithJosh** [Delors/delors.github.io#93]
In der Vorlesung zu HTML Grundlagen fehlt das "g" in "michael-eichberg.de".
https://delors.github.io/web-html/folien.rst.html?ld-slide-no=5
![missing g](https://github.com/Delors/delors.github.io/assets/134294776/3027e102-d4f1-492f-8ebf-a75c2e90f758)

**Comment by Delors** [comment]
Danke! Im nächsten Release behoben.
