### ISSUE TITLE
Historie nicht sichtbar

### ISSUE THREAD

**Issue by NechZ** [Delors/delors.github.io#94]
![image](https://github.com/Delors/delors.github.io/assets/53906238/c2345648-0af5-48c9-b6f2-3ff2a3ceaea7)
Wenn man das HTML Dokument https://delors.github.io/web-html/folien.rst.html?ld-slide-no=2 öffnet ist die Timeline im Gegensatz zum PDF Dokument nicht sichtbar

**Comment by Delors** [comment]
Können Sie mir bitte kurz schreiben welcher Browser auf welchem OS dieses Verhalten zeigt?

**Comment by Delors** [comment]
Mit dem nächsten Release behoben.
