### ISSUE TITLE
Übungsaufgabe Mix Column Transformation

### ISSUE THREAD

**Issue by n4menlos** [Delors/delors.github.io#95]
Guten Abend Herr Prof. Eichberg,

beim Wiederholen Ihrer Vorlesungsunterlagen (https://delors.github.io/sec-aes/folien.de.rst.html) ist uns in der Übungsaufgabe zur Mix Column Transformation ein Fehler aufgefallen. Die letzte Spalte des Lösungstableaus ist nicht korrekt. Die richtigen Werte müssten sein:
9A
CB
86
CA

Mit freundlich Grüßen in einen ruhigen Sonntagabend,

Jens Schmelter, Jonas Hörner und Valentin Naumann

​

**Comment by Delors** [comment]
Sie haben auf jeden Fall recht! Vielen Dank für den Hinweis. Ich haben den Fehler behoben und er wird mit der nächsten Aktualisierung weg sein.
